import * as Crypto from "expo-crypto";
import {
  ExerciseCategory,
  ExerciseDifficulty,
  ExerciseEquipment,
  ExerciseUnit,
} from "./Enums";
import { Exercise } from "./Types";

// Helper for generating UUIDs
const generateId = () => {
  try {
    if (Crypto.randomUUID) {
      return Crypto.randomUUID();
    }
  } catch (e) {}
  // Simple fallback
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
    var r = (Math.random() * 16) | 0,
      v = c == "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

export const defaultExercises: Exercise[] = [
  // PUSH - Beginner
  {
    id: generateId(),
    name: "Push Up",
    category: ExerciseCategory.PUSH,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Standard push up ensuring full range of motion.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 15,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Knee Push Up",
    category: ExerciseCategory.PUSH,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Push up on knees for building strength.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 15,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  // PULL - Beginner
  {
    id: generateId(),
    name: "Australian Pull Up",
    category: ExerciseCategory.PULL,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Body rows on low bar or rings.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 12,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  // LEGS - Beginner
  {
    id: generateId(),
    name: "Squat",
    category: ExerciseCategory.LEGS,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Standard bodyweight squat.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 20,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Lunge",
    category: ExerciseCategory.LEGS,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Forward stepping lunge.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 12,
    unit: ExerciseUnit.REPS,
    is_unilateral: true,
  },
  // CORE - Beginner
  {
    id: generateId(),
    name: "Plank",
    category: ExerciseCategory.CORE,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Static hold on elbows and toes.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 45,
    unit: ExerciseUnit.SECS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Crunches",
    category: ExerciseCategory.CORE,
    difficulty: ExerciseDifficulty.BEGINNER,
    description: "Abdominal crunches.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 20,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },

  // PUSH - Intermediate
  {
    id: generateId(),
    name: "Diamond Push Up",
    category: ExerciseCategory.PUSH,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Hands close together forming a diamond shape.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 12,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Dip",
    category: ExerciseCategory.PUSH,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Dip usually performed on parallel bars or rings.",
    equipment: ExerciseEquipment.PARALLETTES,
    default_reps: 10,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Pike Push Up",
    category: ExerciseCategory.PUSH,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Hips high, pushing vertically for shoulders.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 10,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  // PULL - Intermediate
  {
    id: generateId(),
    name: "Pull Up",
    category: ExerciseCategory.PULL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Standard overhand grip pull up.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 8,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Chin Up",
    category: ExerciseCategory.PULL,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Underhand grip pull up, biceps bias.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 8,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  // LEGS - Intermediate
  {
    id: generateId(),
    name: "Jump Squat",
    category: ExerciseCategory.LEGS,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Explosive squat with a jump at the top.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 15,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  // CORE - Intermediate
  {
    id: generateId(),
    name: "L-Sit",
    category: ExerciseCategory.CORE,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Holding legs horizontal with torso vertical.",
    equipment: ExerciseEquipment.PARALLETTES,
    default_reps: 15,
    unit: ExerciseUnit.SECS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Leg Raise",
    category: ExerciseCategory.CORE,
    difficulty: ExerciseDifficulty.INTERMEDIATE,
    description: "Hanging leg raise to bar.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 10,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },

  // ADVANCED / ELITE
  {
    id: generateId(),
    name: "Muscle Up",
    category: ExerciseCategory.PULL,
    difficulty: ExerciseDifficulty.ELITE,
    description: "Explosive pull from hang to support.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 3,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Handstand Push Up",
    category: ExerciseCategory.PUSH,
    difficulty: ExerciseDifficulty.ADVANCED,
    description: "Vertical press while in a handstand.",
    equipment: ExerciseEquipment.FLOOR, // Or parallettes
    default_reps: 5,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Front Lever",
    category: ExerciseCategory.SKILLS,
    difficulty: ExerciseDifficulty.ELITE,
    description: "Static hold with body horizontal facing up.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 5,
    unit: ExerciseUnit.SECS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Back Lever",
    category: ExerciseCategory.SKILLS,
    difficulty: ExerciseDifficulty.ADVANCED,
    description: "Static hold with body horizontal facing down.",
    equipment: ExerciseEquipment.PULL_UP_BAR,
    default_reps: 10,
    unit: ExerciseUnit.SECS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Planche",
    category: ExerciseCategory.SKILLS,
    difficulty: ExerciseDifficulty.ELITE,
    description: "Static hold with body horizontal supported by arms.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 5,
    unit: ExerciseUnit.SECS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Pistol Squat",
    category: ExerciseCategory.LEGS,
    difficulty: ExerciseDifficulty.ADVANCED,
    description: "Single leg squat.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 5,
    unit: ExerciseUnit.REPS,
    is_unilateral: true,
  },
  {
    id: generateId(),
    name: "Dragon Flag",
    category: ExerciseCategory.CORE,
    difficulty: ExerciseDifficulty.ELITE,
    description: "Body lever from shoulders.",
    equipment: ExerciseEquipment.FLOOR,
    default_reps: 5,
    unit: ExerciseUnit.REPS,
    is_unilateral: false,
  },
  {
    id: generateId(),
    name: "Human Flag",
    category: ExerciseCategory.SKILLS,
    difficulty: ExerciseDifficulty.ELITE,
    description: "Sideways static hold.",
    equipment: ExerciseEquipment.STALL_BAR,
    default_reps: 5,
    unit: ExerciseUnit.SECS,
    is_unilateral: true,
  },
];
