/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Activity"][];
                        "application/json": components["schemas"]["Activity"][];
                        "text/json": components["schemas"]["Activity"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateActivityDto"];
                    "text/json": components["schemas"]["CreateActivityDto"];
                    "application/*+json": components["schemas"]["CreateActivityDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Activity"];
                        "application/json": components["schemas"]["Activity"];
                        "text/json": components["schemas"]["Activity"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/body-weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BodyWeightEntry"][];
                        "application/json": components["schemas"]["BodyWeightEntry"][];
                        "text/json": components["schemas"]["BodyWeightEntry"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateBodyWeightDto"];
                    "text/json": components["schemas"]["CreateBodyWeightDto"];
                    "application/*+json": components["schemas"]["CreateBodyWeightDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BodyWeightEntry"];
                        "application/json": components["schemas"]["BodyWeightEntry"];
                        "text/json": components["schemas"]["BodyWeightEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/body-weight/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercise-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExerciseCategory"][];
                        "application/json": components["schemas"]["ExerciseCategory"][];
                        "text/json": components["schemas"]["ExerciseCategory"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeInactive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExerciseDto"][];
                        "application/json": components["schemas"]["ExerciseDto"][];
                        "text/json": components["schemas"]["ExerciseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateExerciseDto"];
                    "text/json": components["schemas"]["CreateExerciseDto"];
                    "application/*+json": components["schemas"]["CreateExerciseDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Exercise"];
                        "application/json": components["schemas"]["Exercise"];
                        "text/json": components["schemas"]["Exercise"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExerciseDto"];
                        "application/json": components["schemas"]["ExerciseDto"];
                        "text/json": components["schemas"]["ExerciseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/muscle-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MuscleGroup"][];
                        "application/json": components["schemas"]["MuscleGroup"][];
                        "text/json": components["schemas"]["MuscleGroup"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planned-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlannedSession"][];
                        "application/json": components["schemas"]["PlannedSession"][];
                        "text/json": components["schemas"]["PlannedSession"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePlannedSessionDto"];
                    "text/json": components["schemas"]["CreatePlannedSessionDto"];
                    "application/*+json": components["schemas"]["CreatePlannedSessionDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlannedSession"];
                        "application/json": components["schemas"]["PlannedSession"];
                        "text/json": components["schemas"]["PlannedSession"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planned-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlannedSession"];
                        "application/json": components["schemas"]["PlannedSession"];
                        "text/json": components["schemas"]["PlannedSession"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdatePlannedSessionDto"];
                    "text/json": components["schemas"]["UpdatePlannedSessionDto"];
                    "application/*+json": components["schemas"]["UpdatePlannedSessionDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlannedSession"];
                        "application/json": components["schemas"]["PlannedSession"];
                        "text/json": components["schemas"]["PlannedSession"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Routine"][];
                        "application/json": components["schemas"]["Routine"][];
                        "text/json": components["schemas"]["Routine"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateRoutineDto"];
                    "text/json": components["schemas"]["CreateRoutineDto"];
                    "application/*+json": components["schemas"]["CreateRoutineDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Routine"];
                        "application/json": components["schemas"]["Routine"];
                        "text/json": components["schemas"]["Routine"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Routine"];
                        "application/json": components["schemas"]["Routine"];
                        "text/json": components["schemas"]["Routine"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRoutineDto"];
                    "text/json": components["schemas"]["UpdateRoutineDto"];
                    "application/*+json": components["schemas"]["UpdateRoutineDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Routine"];
                        "application/json": components["schemas"]["Routine"];
                        "text/json": components["schemas"]["Routine"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Session"][];
                        "application/json": components["schemas"]["Session"][];
                        "text/json": components["schemas"]["Session"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSessionDto"];
                    "text/json": components["schemas"]["CreateSessionDto"];
                    "application/*+json": components["schemas"]["CreateSessionDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Session"];
                        "application/json": components["schemas"]["Session"];
                        "text/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Session"];
                        "application/json": components["schemas"]["Session"];
                        "text/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfile"];
                        "application/json": components["schemas"]["UserProfile"];
                        "text/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserProfileDto"];
                    "text/json": components["schemas"]["UpdateUserProfileDto"];
                    "application/*+json": components["schemas"]["UpdateUserProfileDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile/apply-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApplyStatsDto"];
                    "text/json": components["schemas"]["ApplyStatsDto"];
                    "application/*+json": components["schemas"]["ApplyStatsDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplyStatsResponseDto"];
                        "application/json": components["schemas"]["ApplyStatsResponseDto"];
                        "text/json": components["schemas"]["ApplyStatsResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-profile/reset-streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfile"];
                        "application/json": components["schemas"]["UserProfile"];
                        "text/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            performedAt?: string;
            type: string;
            /** Format: int32 */
            durationSeconds?: number | null;
            /** Format: double */
            distanceMeters?: number | null;
            /** Format: int32 */
            steps?: number | null;
            notes?: string | null;
            source?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ApplyStatsDto: {
            /** Format: int32 */
            xpGained?: number;
            /** Format: int32 */
            repsGained?: number;
        };
        ApplyStatsResponseDto: {
            profile?: components["schemas"]["UserProfile"];
            streakBreakSuggested?: boolean;
            /** Format: int32 */
            daysSinceLastActivity?: number | null;
        };
        BodyWeightEntry: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            measuredAt?: string;
            /** Format: double */
            weightKg?: number;
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateActivityDto: {
            /** Format: date-time */
            performedAt?: string;
            type: string;
            /** Format: int32 */
            durationSeconds?: number | null;
            /** Format: double */
            distanceMeters?: number | null;
            /** Format: int32 */
            steps?: number | null;
            notes?: string | null;
            source?: string | null;
        };
        CreateBodyWeightDto: {
            /** Format: date */
            measuredAt: string;
            /** Format: double */
            weightKg: number;
            notes?: string | null;
        };
        CreateExerciseDto: {
            name: string;
            /** Format: int32 */
            categoryId?: number | null;
            category?: string | null;
            /** Format: uuid */
            baseExerciseId?: string | null;
            difficulty: string;
            description?: string | null;
            equipment: string;
            /** Format: int32 */
            defaultReps?: number;
            unit: string;
            isUnilateral?: boolean;
            isDefault?: boolean;
            muscleGroups?: components["schemas"]["ExerciseMuscleGroupDto"][] | null;
        };
        CreatePlannedSessionDto: {
            /** Format: uuid */
            routineId?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string | null;
            recurrenceType: string;
            /** Format: int32 */
            daysOfWeek?: number;
            /** Format: int32 */
            intervalDays?: number | null;
        };
        CreateRoutineDto: {
            name: string;
            color: string;
            exercises?: components["schemas"]["CreateRoutineExerciseDto"][] | null;
        };
        CreateRoutineExerciseDto: {
            /** Format: uuid */
            exerciseId?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: int32 */
            targetSets?: number | null;
            /** Format: int32 */
            targetReps?: number | null;
            notes?: string | null;
            sets?: components["schemas"]["CreateRoutineExerciseSetDto"][] | null;
        };
        CreateRoutineExerciseSetDto: {
            /** Format: int32 */
            setIndex?: number;
            /** Format: int32 */
            targetReps?: number | null;
            /** Format: int32 */
            targetSeconds?: number | null;
            /** Format: int32 */
            restSeconds?: number | null;
        };
        CreateSessionDto: {
            /** Format: uuid */
            routineId?: string | null;
            titleSnapshot: string;
            /** Format: date-time */
            performedAt?: string;
            /** Format: int32 */
            durationSeconds?: number | null;
            notes?: string | null;
            exercises?: components["schemas"]["CreateSessionExerciseDto"][] | null;
        };
        CreateSessionExerciseDto: {
            /** Format: uuid */
            exerciseId?: string;
            /** Format: int32 */
            orderIndex?: number;
            exerciseNameSnapshot: string;
            unitSnapshot: string;
            sets?: components["schemas"]["CreateSessionSetDto"][] | null;
        };
        CreateSessionSetDto: {
            /** Format: int32 */
            setIndex?: number;
            /** Format: int32 */
            reps?: number | null;
            /** Format: double */
            weight?: number | null;
            /** Format: int32 */
            seconds?: number | null;
        };
        Exercise: {
            /** Format: uuid */
            id?: string;
            name: string;
            code?: string | null;
            isActive?: boolean;
            categoryLegacy: string;
            difficulty: string;
            description?: string | null;
            equipment: string;
            /** Format: int32 */
            defaultReps?: number;
            unit: string;
            isUnilateral?: boolean;
            isDefault?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int32 */
            categoryId?: number;
            category?: components["schemas"]["ExerciseCategory"];
            /** Format: uuid */
            baseExerciseId?: string | null;
            baseExercise?: components["schemas"]["Exercise"];
            variants?: components["schemas"]["Exercise"][] | null;
            exerciseMuscleGroups?: components["schemas"]["ExerciseMuscleGroup"][] | null;
        };
        ExerciseCategory: {
            /** Format: int32 */
            id?: number;
            slug: string;
            name: string;
            /** Format: int32 */
            orderIndex?: number;
            isActive?: boolean;
        };
        ExerciseCategoryDto: {
            /** Format: int32 */
            id?: number;
            slug?: string | null;
            name?: string | null;
            /** Format: int32 */
            orderIndex?: number;
            isActive?: boolean;
        };
        ExerciseDto: {
            /** Format: uuid */
            id?: string;
            code?: string | null;
            name?: string | null;
            category?: components["schemas"]["ExerciseCategoryDto"];
            difficulty?: string | null;
            equipment?: string | null;
            description?: string | null;
            /** Format: int32 */
            defaultReps?: number;
            unit?: string | null;
            isUnilateral?: boolean;
            isDefault?: boolean;
            isActive?: boolean;
            /** Format: uuid */
            baseExerciseId?: string | null;
            baseExercise?: components["schemas"]["ExerciseDto"];
            variants?: components["schemas"]["ExerciseDto"][] | null;
            exerciseMuscleGroups?: components["schemas"]["ExerciseMuscleGroupDto"][] | null;
        };
        ExerciseMuscleGroup: {
            /** Format: uuid */
            exerciseId?: string;
            exercise?: components["schemas"]["Exercise"];
            /** Format: int32 */
            muscleGroupId?: number;
            muscleGroup?: components["schemas"]["MuscleGroup"];
            /** Format: int32 */
            impact?: number;
            effect: string;
            /** Format: int32 */
            share?: number | null;
        };
        ExerciseMuscleGroupDto: {
            code: string;
            /** Format: int32 */
            impact?: number;
            effect: string;
            /** Format: int32 */
            share?: number | null;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token?: string | null;
            /** Format: date-time */
            expiresAt?: string;
        };
        MuscleGroup: {
            /** Format: int32 */
            id?: number;
            code: string;
            side: string;
            /** Format: int32 */
            displayOrder?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PlannedSession: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            routineId?: string;
            routine?: components["schemas"]["Routine"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string | null;
            recurrenceType: string;
            /** Format: int32 */
            daysOfWeek?: number;
            /** Format: int32 */
            intervalDays?: number | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        Routine: {
            /** Format: uuid */
            id?: string;
            name: string;
            color: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            exercises?: components["schemas"]["RoutineExercise"][] | null;
        };
        RoutineExercise: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            routineId?: string;
            routine?: components["schemas"]["Routine"];
            /** Format: uuid */
            exerciseId?: string;
            exercise?: components["schemas"]["Exercise"];
            /** Format: int32 */
            orderIndex?: number;
            /** Format: int32 */
            targetSets?: number | null;
            /** Format: int32 */
            targetReps?: number | null;
            notes?: string | null;
            sets?: components["schemas"]["RoutineExerciseSet"][] | null;
        };
        RoutineExerciseSet: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            routineExerciseId: string;
            routineExercise?: components["schemas"]["RoutineExercise"];
            /** Format: int32 */
            setIndex?: number;
            /** Format: int32 */
            targetReps?: number | null;
            /** Format: int32 */
            targetSeconds?: number | null;
            /** Format: int32 */
            restSeconds?: number | null;
        };
        Session: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            routineId?: string | null;
            routine?: components["schemas"]["Routine"];
            titleSnapshot: string;
            /** Format: date-time */
            performedAt?: string;
            /** Format: int32 */
            durationSeconds?: number | null;
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            sessionExercises?: components["schemas"]["SessionExercise"][] | null;
        };
        SessionExercise: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sessionId?: string;
            session?: components["schemas"]["Session"];
            /** Format: uuid */
            exerciseId?: string;
            exercise?: components["schemas"]["Exercise"];
            /** Format: int32 */
            orderIndex?: number;
            exerciseNameSnapshot: string;
            unitSnapshot: string;
            /** Format: date-time */
            createdAt?: string;
            sets?: components["schemas"]["SessionSet"][] | null;
        };
        SessionSet: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sessionExerciseId?: string;
            sessionExercise?: components["schemas"]["SessionExercise"];
            /** Format: int32 */
            setIndex?: number;
            /** Format: int32 */
            reps?: number | null;
            /** Format: double */
            weight?: number | null;
            /** Format: int32 */
            seconds?: number | null;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdatePlannedSessionDto: {
            /** Format: uuid */
            routineId?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string | null;
            recurrenceType: string;
            /** Format: int32 */
            daysOfWeek?: number;
            /** Format: int32 */
            intervalDays?: number | null;
        };
        UpdateRoutineDto: {
            name: string;
            color: string;
            exercises?: components["schemas"]["CreateRoutineExerciseDto"][] | null;
        };
        UpdateUserProfileDto: {
            /** Format: int32 */
            level?: number;
            /** Format: int32 */
            xp?: number;
            /** Format: int32 */
            streakCurrent?: number;
            /** Format: int32 */
            streakBest?: number;
            /** Format: int32 */
            totalReps?: number;
        };
        UserProfile: {
            id?: string | null;
            /** Format: int32 */
            level?: number;
            /** Format: int32 */
            xp?: number;
            /** Format: int32 */
            streakCurrent?: number;
            /** Format: int32 */
            streakBest?: number;
            /** Format: date-time */
            streakStartDate?: string | null;
            /** Format: date-time */
            lastActivityDate?: string | null;
            /** Format: int32 */
            totalReps?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
