// Auto-generated by scripts/generate-mock-exercises.js — do not edit manually
import { ExerciseCategoryModel } from "@/constants/Types";

const MOCK_CATEGORIES: ExerciseCategoryModel[] = [
  { id: 1, slug: "push", name: "Push", orderIndex: 10 },
  { id: 2, slug: "pull", name: "Pull", orderIndex: 20 },
  { id: 3, slug: "legs", name: "Legs", orderIndex: 30 },
  { id: 4, slug: "core", name: "Core", orderIndex: 40 },
  { id: 5, slug: "neck", name: "Neck", orderIndex: 50 },
  { id: 6, slug: "mobility", name: "Mobility", orderIndex: 60 },
  { id: 7, slug: "skill", name: "Skill", orderIndex: 70 },
  { id: 8, slug: "stretch", name: "Stretch", orderIndex: 80 },
  { id: 9, slug: "cardio", name: "Cardio", orderIndex: 90 }
];

export default MOCK_CATEGORIES;
